### ISSUE TITLE
Support --cache-from in publish job

### ISSUE THREAD

**Issue by Beanow** [CircleCI-Public/docker-orb#15] opened 2019-08-28 17:25 UTC
The `docker build --cache-from` option is a very common method for increasing CI build speeds.
For this to work, it's usually preceded by pulling the same images you want to use here.

This need for first pulling the images, I think warrants a separate option for the publish job.
As using `extra_build_args` would not include the pull step.

**Comment by RanadeepPolavarapu** [comment] 2019-09-28 21:20
I'll take this.

**Comment by KyleTryon** [comment] 2019-10-04 17:47
duplicate of https://github.com/CircleCI-Public/aws-ecr-orb/issues/4

**Closed by KyleTryon** 2019-10-04 17:47 UTC
Labels: hacktoberfest, orbtoberfest
